name: First Workflaw
on:
    push: 
        branches:
            - main
jobs:
  job1:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout
           uses: actions/checkout@4
         - name: Print Hello World
           run: echo "Hello World" 