name: Main Deployment

on:
  push:
    branches:
        - main



jobs:

 docker_build:
    runs-on: ubuntu-latest
    needs: build-test-sonarqube
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        
        run: docker build -t ghcr.io/${{ github.repository_owner }}/go-hello-world:${{ github.sha }} .

      # Step 10: Login to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 11: Push Docker image
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/go-hello-world:${{ github.sha }}
