name: PR Tests & SonarCloud

on: 
  pull_request:
    branches:
       - '**'
  push:
    branches:
      - main

jobs:
  build-test-sonarqube:
    runs-on: ubuntu-latest

    

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
    

      # Step 2: Set up Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

     

    
      - name: Install dependencies
        run: go mod tidy

      # Step 5: Lint
      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest


  unit_tests:
     runs-on: ubuntu-latest
     needs: build-test-sonarqube
     steps:
      - uses: actions/checkout@v3
      - name: Set up GO 
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Run unit tests and generate unit coverage report
        run: |
          mkdir -p test-results
           
          go test -coverprofile=test-results/unit.coverage.out -covermode=atomic ./...

      - name: Upload unit tests
        uses: actions/upload-artifact@v4
        with: 
          name: unit-coverage
          path: test-results/unit.coverage.out
          

  integration_tests:
     runs-on: ubuntu-latest
     needs: [build-test-sonarqube, unit_tests]
     steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Download unit coverage
        uses: actions/download-artifact@v4
        with:
          name: unit-coverage
          path: test-results/

      - name: Run integration tests with coverage
        run: |
          mkdir -p test-results
          export INTEGRATION=true
          go test -coverprofile=test-results/integration.coverage.out -covermode=atomic ./... -run="^TestIntegration"
          echo "mode:atomic" > test-results/combined.coverage.out
          tail -n +2 test-results/unit.coverage.out >> test-results/combined.coverage.out
          tail -n +2 test-results/integration.coverage.out >> test-results/combined.coverage.out

        
        

      - name: Set up SonarCloud
        if: ${{ env.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with: 
          args: > 
             -Dsonar.projectKey=dpetrov-sap_ums
             -Dsonar.organization=dpetrov-sap
             -Dsonar.go.coverage.reportPaths=test-results/combined.coverage.out

       

 
  docker_build:
    runs-on: ubuntu-latest
    needs: build-test-sonarqube

    if: github.event_name == 'push'
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (no push on PR)
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: ./Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/go-hello-world:${{ github.sha }}

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Step 11: Push Docker image
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/go-hello-world:${{ github.sha }}